baseURL = "https://okmechak.github.io/"
languageCode = "ua"
defaultContentLanguage = "ua"
title = "DWNM"
theme = "ticky-theme"
publishDir = "okmechak.github.io"
enableEmoji = true
#appear in the footer
copyright = "Copyright © 2019 Oleg Kmechak  All Rights Reserved."

# English
[languages.en]
    languageName = "English"
[languages.ua]
    languageName = "Українська"

    # Footer menu 1
    [[languages.ua.params.footer_menus]]
        name = ""
        menu = "links"

    [[languages.ua.menu.links]]
        url = "https://github.com/okmechak"
        name = "GitHub"
        weight = 1

    [[languages.ua.menu.links]]
        url = "https://www.linkedin.com/in/oleg-kmechak/"
        name = "Linkedin"
        weight = 2

    [[languages.ua.menu.links]]
        url = "https://www.youtube.com/channel/UCRmxGli1cPA6q6-I2W_IJeA"
        name = "YouTube"
        weight = 3
    
    [[languages.ua.menu.links]]
        url = "https://soundcloud.com/rain_must_fall"
        name = "SoundCloud"
        weight = 4


[params]