baseURL = "https://okmechak.github.io/"
languageCode = "en-us"
title = "DWNM"
theme = "ticky-theme"
publishDir = "okmechak.github.io"
enableEmoji = true
#appear in the footer
copyright = "© 2018 Copyright Text"

# English
[languages.en]
    languageName = "English"
    
    # Main menu
    #[[languages.en.menu.main]]
    #    url = "/"
    #    name = "Home"
    #    weight = 1
        
    # Footer menu 1
    [[languages.en.menu.footer1]]
        url = "#"
        name = "Service 1"
        weight = 1

    [[languages.en.menu.footer1]]
        url = "#"
        name = "Service 2"
        weight = 2

    # Footer menu 2
    [[languages.en.menu.footer2]]
        url = "/"
        name = "Home"
        weight = 1

    [[languages.en.menu.footer2]]
        url = "/about/"
        name = "About"
        weight = 2

    # Include menus in footer
    [[languages.en.params.footer_menus]]
        name = "Services"
        menu = "footer2"

    [[languages.en.params.footer_menus]]
        name = "Links"
        menu = "footer1"




[languages.ua]
    languageName = "Українська"
    # Main menu
    #[[languages.ua.menu.main]]
    #    url = "/ua/"
    #    name = "Домашня сторінка"
    #    weight = 1

    # Footer menu 1
    [[languages.ua.menu.footer1]]
        url = "#"
        name = "Сервіс 1"
        weight = 1

    [[languages.ua.menu.footer1]]
        url = "#"
        name = "Сервіс 2"
        weight = 2

    # Footer menu 2
    [[languages.ua.menu.footer2]]
        url = "/ua/"
        name = "Домашня сторінка"
        weight = 1

    [[languages.ua.menu.footer2]]
        url = "/про/"
        name = "Про"
        weight = 2

    # Include menus in footer
    [[languages.ua.params.footer_menus]]
        name = "Сервіси"
        menu = "footer2"

    [[languages.ua.params.footer_menus]]
        name = "Посилання"
        menu = "footer1"

[params]